[project]
name = 'Blockchain-Based-Manufacturing-Collaborative-Innovation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.implementation-tracking]
path = 'contracts/implementation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.innovation-challenge]
path = 'contracts/innovation-challenge.clar'
clarity_version = 2
epoch = 2.5

[contracts.manufacturer-verification]
path = 'contracts/manufacturer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
